apiVersion: apps/v1
kind: Deployment
metadata:
  name: navigation-deployment
  labels:
    app: navigation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navigation
  template:
    metadata:
      labels:
        app: navigation
    spec:
      containers:
      - name: navigation
        image: navigation:latest
        ports:
        - containerPort: 8081
