apiVersion: v1
kind: Service
metadata:
  name: navigation
  labels:
    app: navigation
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: navigation
